### ISSUE TITLE
Unclear on How to Run Tests

### ISSUE THREAD

**Issue by ArcaneLG** [deckerous/Journey_Of_The_Voice#22]
I couldn't figure out how to run tests through Godot. I found the "GUT" tab but I wasn't able to run any tests. I got a message saying:

Cannot run tests, you have a configuration error:
*  You do not have any directories set.
Check your settings ----->

I tried to select a test file from the menu on the left to see if that might work, but that didn't seem to change anything. I tried using Run All and running the currently selected file but neither worked.

**Comment by joshcherndev** [comment]
Included more clear instructions for testing including setting the test directory and running individual test files.
