### ISSUE TITLE
Unable to Open Save File on First Attempt

### ISSUE THREAD

**Issue by Dominic-Roser** [deckerous/Journey_Of_The_Voice#28]
When I first tried to open the save file, the game quit and displayed an error message 
"E 0:01:52:0888   global_audio.gd:31 @ get_stream_from_id(): Node not found: "/root/GlobalAudio/bar-theme" (absolute path attempted from "/root/GlobalAudio").
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1790 @ get_node()
  <Stack Trace>  global_audio.gd:31 @ get_stream_from_id()
                 box_breathing.gd:15 @ _ready()
                 area.gd:66 @ go_to_next_minigame()
                 conversation.gd:107 @ end_dialogue()
                 conversation_ui.gd:60 @ handle_dialogue()
                 conversation.gd:91 @ on_dialogue_click()"
But on second attempt after rebooting loading the save file worked fine.

**Comment by joshcherndev** [comment]
Saving reworked. This issue no longer pops up.
