### ISSUE TITLE
First-time Launch Contains Unexpected Pre-existing Save Data

### ISSUE THREAD

**Issue by adamben04** [deckerous/Journey_Of_The_Voice#29]
I just downloaded and ran the game for the first time, and I noticed there's already a save file in there. I definitely didn't create this save, it seems to be someone else's progress that was accidentally left in. This could be pretty confusing for other new players who are just starting out.
![image](https://github.com/user-attachments/assets/c607e28d-5d16-42b6-8475-83d57d4d9026)

**Comment by joshcherndev** [comment]
This was for the beta build to show off a mid-game chapter.
